# source 'http://rubygems.org'
source 'http://ruby.taobao.org'
#source 'http://127.0.0.1:8808'
gem 'rails', '3.1.1'
# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'
gem 'mysql2'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'will_paginate' #分页

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'


gem 'authlogic', '3.1.0' #用户系统
gem 'ar_mailer_rails3' #发送邮件
gem 'delayed_job' #定时钟

gem 'redis', '2.2.2'

#图片上传

gem 'carrierwave', "0.5.3"
gem 'mini_magick', "3.2"
## linux 下使用 gem 'rmagick'

gem 'rufus-scheduler'

#按如下方式先传统方式安装rmagick 然后copy到app下的gem lib
#gem install rmagick  -v '2.13.1' -- --with-opt-lib='C:\ImageMagick-6.7.6-Q16/lib' --with-opt-include='C:\ImageMagick-6.7.6-Q16/include'

gem 'quick_magick'

#用户系统-邮件找回密码模块
gem 'devise', '2.1.0.rc'
#邀请注册模块
gem 'devise_invitable', '~> 1.0.0'

gem 'rmagick', '2.13.1'

gem 'easy_captcha'

#随机码生成

#过滤日志   WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true
#同时启动应用时不再用webrick 而是用thin
#   先安装 devkit 和 gem install eventmachine --pre
#gem  'daemons','1.1.8'

#gem "eventmachine", "~> 0.12.10"
#gem 'thin','1.3.1'


gem 'minitest-reporters', '>= 0.4.1'

gem 'ruby-prof', '0.11.2'

#估计是linux下特有的包

if (RUBY_PLATFORM =~ /i386-mingw32/).nil?
  gem 'execjs'
  gem 'therubyracer'
end


group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
